config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  
  root to: "home#index"

  namespace :creator do
    get 'dashboard', to: "dashboard#index"
    get 'bazaar/browse',    to: "bazaar#browse"

    resources :conversations, only: [:index, :show] do
      resources :messages, only: [:create]
    end
    get 'conversations/publisher/:id', to: "conversations#publisher"
    resources :videos
    resources :publishers, only: [:show]
  end

  namespace :publisher do
    get 'dashboard', to: "dashboard#index"
    get 'bazaar',    to: "bazaar#browse"

    resources :creators, only: [:show]
    resources :conversations, only: [:index, :show] do
      resources :messages, only: [:create]
    end
    get 'conversations/creator/:id', to: "conversations#creator"
    resources :videos
  end

  get '404', to: 'application#render_404'
  get '*unmatched_route', to: 'application#render_404'
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :participants, dependent: :destroy
  has_many :companies, through: :participants

  def user_ids
    User.where("users.company_id IN (?)", companies.ids).ids
  end
end

app/controllers/creator/base_controller.rb
class Creator::BaseController < AuthorizedController
  before_action :assure_creator

  protected

  def assure_creator
    return if current_user.company.creator?
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/creator/bazaar_controller.rb
class Creator::BazaarController < Creator::BaseController
  def browse
    @publishers = Company.where(kind: 'publisher').order('id ASC').limit(6)
    @publishers2 = Company.where(kind: 'publisher').order('id DESC').limit(4)
  end
end

app/controllers/creator/conversations_controller.rb
class Creator::ConversationsController < Creator::BaseController
  def index
    get_left_bar
  end

  def show
    get_left_bar
    @conversation = current_user.company.conversations.find_by(id: params[:id])
    if @conversation.nil?
      redirect_to creator_conversations_path
    else
      @message = @conversation.messages.new()
      @company = @conversation.companies.where("companies.id != ?", current_user.company.id).first
      Message.all.where('user_id NOT IN (?) AND conversation_id = ?', current_user.company.users.ids, @conversation.id).update_all(read: true)
    end
  end

  def publisher
    get_left_bar
    publisher = Company.find(params[:id])
    pub_convo_ids = publisher.conversations.ids
    cu_convo_ids = current_user.company.conversations.ids
    found = pub_convo_ids & cu_convo_ids
    @conversation = Conversation.find_by(id: found.first)
    if @conversation.nil?
      @conversation = Conversation.create()
      @conversation.participants.create(company_id: current_user.company.id)
      @conversation.participants.create(company_id: publisher.id)
    end
    @message = @conversation.messages.new()
    @company = @conversation.companies.where("companies.id != ?", current_user.company.id).first
    redirect_to creator_conversation_path(@conversation.messages.first.conversation_id)
  end

  private

  def get_left_bar
    convo_ids = current_user.company.conversations.ids
    @messages = Message.includes(:conversation)
                        .where('messages.id IN (
                            SELECT MAX(messages.id)
                            FROM messages
                            WHERE messages.conversation_id
                            IN (?)
                            GROUP BY messages.conversation_id
                          )', convo_ids)
                        .order("created_at DESC", "id DESC")
  end
end

app/controllers/creator/dashboard_controller.rb
class Creator::DashboardController < Creator::BaseController
  def index
    @videos = current_user.company.videos.includes(:genre)
    @viewership = [
      { created_at: 1.hour.ago.beginning_of_hour.strftime("%H:%M"), views: 566 },
      { created_at: 2.hours.ago.beginning_of_hour.strftime("%H:%M"), views: 400 },
      { created_at: 3.hours.ago.beginning_of_hour.strftime("%H:%M"), views: 303 },
      { created_at: 4.hours.ago.beginning_of_hour.strftime("%H:%M"), views: 353 },
      { created_at: 5.hours.ago.beginning_of_hour.strftime("%H:%M"), views: 210 },
      { created_at: 6.hours.ago.beginning_of_hour.strftime("%H:%M"), views: 308 }
    ]
    @publishers = Company.where(kind: "publisher")
  end
end

app/controllers/creator/messages_controller.rb
class Creator::MessagesController < Creator::BaseController
  def create
    @conversation = current_user.company.conversations.find(params[:conversation_id])
    @message = @conversation.messages.new(message_params)
    if @message.save
      ids = @conversation.companies.ids
      filtered_ids = ids - [current_user.company.id]
      filtered_ids.each do |id|
        ActionCable.server.broadcast "company_#{id}_channel",
          { message: {
              id: @message.id,
              body: @message.body,
              company_name: @message.company.name,
              conversation_id: @conversation.id,
              message_time: @message.message_time,
              cover_image_url: current_user.company.cover_image_url,
              to_kind: "publisher"
            },
            user: current_user
          }
      end
      respond_to do |format|
        format.js
      end
    else
      redirect_to creator_conversation_url(@conversation.id)
    end
  end

  protected

  def message_params
    params.require(:message).permit(:body, :user_id, :conversation_id).merge(user_id: current_user.id, company_id: current_user.company.id)
  end
end

app/controllers/creator/publishers_controller.rb
class Creator::PublishersController < Creator::BaseController
  def show
    @publisher = Company.where(kind: 'publisher').find(params[:id])
    @videos = Video.all.first ? Video.all.limit(4) : []
  end
end

app/controllers/creator/videos_controller.rb
class Creator::VideosController < Creator::BaseController
  def index
    @videos = current_user.company.videos.limit(4)
  end

  def show
    @video = current_user.company.videos.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def new
    set_s3_direct_post
    @video = current_user.company.videos.new()
    respond_to do |format|
      format.js
    end
  end

  def create
    set_s3_direct_post
    @video = current_user.company.videos.new(video_params)
    if @video.save
      redirect_to creator_dashboard_path
    else
      redirect_to creator_dashboard_path
    end
  end

  protected

  def video_params
    params.require(:video).permit(:name, :url, :description, :thumbnail, :genre_id)
  end

  def set_s3_direct_post
    bucket = Aws::S3::Bucket.new(
      access_key_id: ENV['AWS_ACCESS_KEY_ID'],
      secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
      region: 'us-west-2',
      name: ENV['S3_BUCKET']
    )
    @s3_direct_post = bucket.presigned_post(key: "uploads/#{SecureRandom.uuid}${filename}", success_action_status: '201', acl: 'public-read')
  end
end

app/controllers/publisher/conversations_controller.rb
class Publisher::ConversationsController < Publisher::BaseController
  def index
    get_left_bar
  end

  def show
    get_left_bar
    @conversation = current_user.company.conversations.find_by(id: params[:id])
    if @conversation.nil?
      redirect_to creator_conversations_path
    else
      @message = @conversation.messages.new()
      @company = @conversation.companies.where("companies.id != ?", current_user.company.id).first
      Message.all.where('user_id NOT IN (?) AND conversation_id = ?', current_user.company.users.ids, @conversation.id).update_all(read: true)
    end
  end

  def creator
    get_left_bar
    creator = Company.find(params[:id])
    pub_convo_ids = creator.conversations.ids
    cu_convo_ids = current_user.company.conversations.ids
    found = pub_convo_ids & cu_convo_ids
    @conversation = Conversation.find_by(id: found.first)
    if @conversation.nil?
      @conversation = Conversation.create()
      @conversation.participants.create(company_id: current_user.company.id)
      @conversation.participants.create(company_id: creator.id)
    end
    @message = @conversation.messages.new()
    @company = @conversation.companies.where("companies.id != ?", current_user.company.id).first
    redirect_to publisher_conversation_path(@conversation.messages.first.conversation_id)
  end

  private

  def get_left_bar
    convo_ids = current_user.company.conversations.ids
    @messages = Message.includes(:conversation)
                        .where('messages.id IN (
                            SELECT MAX(messages.id)
                            FROM messages
                            WHERE messages.conversation_id
                            IN (?)
                            GROUP BY messages.conversation_id
                          )', convo_ids)
                        .order("created_at DESC", "id DESC")
  end

end

app/controllers/publisher/creators_controller.rb
class Publisher::CreatorsController < Publisher::BaseController
  def show
    @creator = Company.where(kind: 'creator').all.find(params[:id])
    @videos = @creator.videos.limit(4)
  end
end

app/views/creator/conversations/_left.html.erb
  <div class="conversation-column">
    <div class="column-header">
      <span class="column-title"><strong>Messages</strong></span>
    </div>
    <div class="conversation-content" id="conversation-overview">
      <% messages.includes(user: :company).each do |message| %>
        <%= link_to creator_conversation_path(message.conversation_id), id: "chat-item-#{message.conversation_id}" do %>
          <div class="chat-item" data-conversation-id="<%= message.id %>">
            <img src="<%= message.user.company.cover_image_url %>" />
            <div class="chat-item-details">
              <div>
                <span>
                  <strong><%= message.company_chat_name(current_user.company) %></strong>
                </span>
              </div>
              <div>
                <span class="chat-item-text">
                  <%= message.user.name %>: <%= message.body%>
                </span>
              </div>
            </div>
            <% if message.conversation_unread(current_user) %>
              <span class="chat-item-unread"></span>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

app/views/creator/conversations/_message.html.erb
<% @conversation.messages.order('created_at', 'id').each do |message| %>
  <div>
    <div class="convo-item-container <%= message.direction(current_user) %>">
      <div class="convo-item-bubble <%= message.direction(current_user) %>">
        <%= message.body %>
      </div>
    </div>
  </div>
<% end %>

app/views/creator/conversations/show.html.erb
<div id ="chat-grid" class="chat-grid" data-company-id="<%= current_user.company.id %>">
  <%= render 'left', messages: @messages %>
  <div id="chat-window" class="conversation-column">
    <div id="convo-body" class="convo-body" data-conversation-id="<%= @conversation.id %>">
      <% @conversation.messages.order('created_at', 'id').each do |message| %>
        <div>
          <div class="convo-item-container <%= message.direction(current_user) %>">
            <div class="convo-item-bubble <%= message.direction(current_user) %>">
              <%= message.body %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="convo-form">
      <%= form_for(@message, url: creator_conversation_messages_path(@conversation.id), remote: true, html: {class: "big-form"} ) do |f| %>
        <%= f.text_area :body, placeholder: 'your message', id: "convo-form-input"  %>
        <div> 
          <%= f.submit 'Send', class: "button-primary" %>
        </div>
      <% end %>
    </div>
  </div>
  <div id="chat-details" class="chat-details">
    <img style="width: 100%; height: 200px" src="<%= @company.cover_image_url %>" />
    <div>
      <div class="chat-details-description">
        <span style="color: #6F3291; font-size: 24px"><%= @company.name %></span>
        <span style="color: #9B9B9B; font-size: 14px"><%= @company.description %></span>

        <span style="color: #6F3291; font-size: 16px">6,788 / Subscribers</span>
        <span style="color: #6F3291; font-size: 16px">26,002 / Views</span>
      </div>
      <div class="chat-details-bottom">
        <div>
          <button class="button-secondary">Website</button>
          <button class="button-secondary">Similar</button>
          <button class="button-secondary">Report</button>
        </div>
        <div>
          <button class="button-secondary">Analytics</button>
          <button class="button-secondary">Settings</button>
          <button class="button-secondary">Contracts</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/creator/conversations/show.js.erb
$("#convo-body").html("<%= escape_javascript(render 'message') %>");
$("#chat-details").html("<%= escape_javascript(render 'details') %>");
var objDiv = document.getElementById("convo-body");
if (objDiv) {
  objDiv.scrollTop = objDiv.scrollHeight
}