config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  
  root to: "home#index"

  namespace :creator do
    get 'dashboard', to: "dashboard#index"
    get 'bazaar/browse',    to: "bazaar#browse"

    resources :conversations, only: [:index, :show] do
      resources :messages, only: [:create]
    end
    get 'conversations/publisher/:id', to: "conversations#publisher"
    resources :videos
    resources :publishers, only: [:show]
  end

  namespace :publisher do
    get 'dashboard', to: "dashboard#index"
    get 'bazaar',    to: "bazaar#browse"

    resources :creators, only: [:show]
    resources :conversations, only: [:index, :show] do
      resources :messages, only: [:create]
    end
    get 'conversations/creator/:id', to: "conversations#creator"
    resources :videos
  end

  get '404', to: 'application#render_404'
  get '*unmatched_route', to: 'application#render_404'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users
  has_many :videos

  has_many :participants
  has_many :conversations, through: :participants
  has_many :mesages

  validates :kind,
    inclusion: { in: ['creator',  'publisher'] }

  def publisher?
    kind === "publisher"
  end

  def creator?
    kind === "creator"
  end
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :participants, dependent: :destroy
  has_many :companies, through: :participants

  def user_ids
    User.where("users.company_id IN (?)", companies.ids).ids
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :videos
  
  validates :name,
    presence: true,
    uniqueness: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
  belongs_to :company

  validates :body,
    presence: true

  def message_time
    created_at.strftime("%m/%d %l:%M %p")
  end

  def company_chat_name(user_company)
    conversation.companies.where("companies.id != ?", user_company.id).first.name
  end

  def other_company_chat_name(user_company)
    conversation.companies.where("companies.id != ?", user_company.id).first.name
  end

  def conversation_unread(current_user)
    conversation.messages.where('messages.company_id != ? AND messages.read = false', current_user.company.id).count > 0
  end

  def direction(current_user)
    if current_user.company.id === user.company.id
      "outbound"
    else
      "inbound"
    end
  end

end

app/models/message_read_state.rb
class MessageReadState < ApplicationRecord
  belongs_to :company
  belongs_to :message
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :conversation
  belongs_to :company
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable

  # optional because 1st user is created before company.
  belongs_to :company, optional: true
  
  has_many :messages

  def conversations
    Conversation.where('user_1_id = ? OR user_2_id = ?', id, id)
  end
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :company
  belongs_to :genre
  has_many :views

  validates :name,
    presence: true
end

app/models/view.rb
class View < ApplicationRecord
  belongs_to :video
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :render_404
  rescue_from ActionController::RoutingError, with: :render_404

  def render_404
    render file: 'public/404.html', status: :not_found, layout: false
  end
end

app/controllers/authorized_controller.rb
class AuthorizedController < ApplicationController
  before_action :authenticate_user!
  before_action :check_unread_messages

  protected

  def check_unread_messages
    user_ids = current_user.company.users.ids
    convo_ids = current_user.company.conversations.ids
    @unread = Message.where('messages.conversation_id IN (?) AND messages.user_id NOT IN (?)', convo_ids, user_ids).where(read: false).count > 0
  end
end

app/controllers/creator/base_controller.rb
class Creator::BaseController < AuthorizedController
  before_action :assure_creator

  protected

  def assure_creator
    return if current_user.company.creator?
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/creator/bazaar_controller.rb
class Creator::BazaarController < Creator::BaseController
  def browse
    @publishers = Company.where(kind: 'publisher').order('id ASC').limit(6)
    @publishers2 = Company.where(kind: 'publisher').order('id DESC').limit(4)
  end
end

app/controllers/creator/videos_controller.rb
class Creator::VideosController < Creator::BaseController
  def index
    @videos = current_user.company.videos.limit(4)
  end

  def show
    @video = current_user.company.videos.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def new
    set_s3_direct_post
    @video = current_user.company.videos.new()
    respond_to do |format|
      format.js
    end
  end

  def create
    set_s3_direct_post
    @video = current_user.company.videos.new(video_params)
    if @video.save
      redirect_to creator_dashboard_path
    else
      redirect_to creator_dashboard_path
    end
  end

  protected

  def video_params
    params.require(:video).permit(:name, :url, :description, :thumbnail, :genre_id)
  end

  def set_s3_direct_post
    bucket = Aws::S3::Bucket.new(
      access_key_id: ENV['AWS_ACCESS_KEY_ID'],
      secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
      region: 'us-west-2',
      name: ENV['S3_BUCKET']
    )
    @s3_direct_post = bucket.presigned_post(key: "uploads/#{SecureRandom.uuid}${filename}", success_action_status: '201', acl: 'public-read')
  end
end

app/controllers/home_controller.rb
class HomeController < AuthorizedController
  def index
    if current_user.company.creator?
      redirect_to creator_dashboard_path
    else
      redirect_to publisher_dashboard_path
    end
  end
end

app/controllers/publisher/base_controller.rb
class Publisher::BaseController < AuthorizedController
  before_action :assure_publisher

  protected

  def assure_publisher
    return if current_user.company.publisher?
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/shared/_creator_navbar.html.erb
<nav class="navbar">
  <div class="logo">
    <img src="/logo.png" alt="LOGO" />
  </div>
  <div class="navbar-links">
    <%= link_to creator_dashboard_path do %>
      <div>
        <span>Dashboard</span>
      </div>
    <% end %>
    <%= link_to creator_conversations_path do %>
      <div id="chat-link">
        <span>Chat</span>
        <% if @unread.present? %>
          <span id="chat-bubble"></span>
        <% end %>
      </div>
    <% end %>
    <%= link_to creator_bazaar_browse_path do %>
      <div>
        <span>Bazaar</span>
      </div>
    <% end %>
  </div>
  <div class="dropdown">
    <div class="drop-btn">
      <%= current_user.company.name %>
    </div>
    <div class="dropdown-content">
      <%= link_to "Profile", root_path %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    </div>
  </div> 
</nav>

app/views/shared/_message.html.erb
<div class="convo-item-container <%= message.direction(user) %>">
  <div class="convo-item-bubble <%= message.direction(user) %>">
    <%= message.body %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar">
  <div class="logo">
    <span>
      Logo
    </span>
  </div>
  <div class="navbar-links">
    <%= link_to "Dashboard", root_path %>
    <%= link_to "Analytics", root_path %>
    <%= link_to "Bazaar", root_path %>
  </div>
  <div class="dropdown">
    <div class="drop-btn">Dropdown 
      <i class="fa fa-caret-down"></i>
    </div>
    <div class="dropdown-content">
      <%= link_to "Profile", root_path %>
      <%= link_to "logout", destroy_user_session_path, method: :delete %>
    </div>
  </div> 
</nav>

app/views/shared/_publisher_navbar.html.erb
<nav class="navbar">
  <div class="logo">
    <img src="/logo.png" alt="LOGO" />
  </div>
  <div class="navbar-links">
    <%= link_to "Dashboard", root_path %>
    <%= link_to publisher_conversations_path do %>
      <div id="chat-link">
        <span>Chat</span>
        <% if @unread.present? %>
          <span id="chat-bubble"></span>
        <% end %>
      </div>
    <% end %>
    <%= link_to "Bazaar", publisher_bazaar_path %>
  </div>
  <div class="dropdown">
    <div class="drop-btn">
      <%= current_user.name %>
    </div>
    <div class="dropdown-content">
      <%= link_to "Profile", root_path %>
      <%= link_to "logout", destroy_user_session_path, method: :delete %>
    </div>
  </div> 
</nav>