config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  
  root to: "home#index"

  namespace :creator do
    get 'dashboard', to: "dashboard#index"
    get 'bazaar/browse',    to: "bazaar#browse"

    resources :conversations, only: [:index, :show] do
      resources :messages, only: [:create]
    end
    get 'conversations/publisher/:id', to: "conversations#publisher"
    resources :videos
    resources :publishers, only: [:show]
  end

  namespace :publisher do
    get 'dashboard', to: "dashboard#index"
    get 'bazaar',    to: "bazaar#browse"

    resources :creators, only: [:show]
    resources :conversations, only: [:index, :show] do
      resources :messages, only: [:create]
    end
    get 'conversations/creator/:id', to: "conversations#creator"
    resources :videos
  end

  get '404', to: 'application#render_404'
  get '*unmatched_route', to: 'application#render_404'
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :company
  belongs_to :genre
  has_many :views

  validates :name,
    presence: true
end

app/controllers/creator/base_controller.rb
class Creator::BaseController < AuthorizedController
  before_action :assure_creator

  protected

  def assure_creator
    return if current_user.company.creator?
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/creator/bazaar_controller.rb
class Creator::BazaarController < Creator::BaseController
  def browse
    @publishers = Company.where(kind: 'publisher').order('id ASC').limit(6)
    @publishers2 = Company.where(kind: 'publisher').order('id DESC').limit(4)
  end
end

app/controllers/creator/conversations_controller.rb
class Creator::ConversationsController < Creator::BaseController
  def index
    get_left_bar
  end

  def show
    get_left_bar
    @conversation = current_user.company.conversations.find_by(id: params[:id])
    if @conversation.nil?
      redirect_to creator_conversations_path
    else
      @message = @conversation.messages.new()
      @company = @conversation.companies.where("companies.id != ?", current_user.company.id).first
      Message.all.where('user_id NOT IN (?) AND conversation_id = ?', current_user.company.users.ids, @conversation.id).update_all(read: true)
    end
  end

  def publisher
    get_left_bar
    publisher = Company.find(params[:id])
    pub_convo_ids = publisher.conversations.ids
    cu_convo_ids = current_user.company.conversations.ids
    found = pub_convo_ids & cu_convo_ids
    @conversation = Conversation.find_by(id: found.first)
    if @conversation.nil?
      @conversation = Conversation.create()
      @conversation.participants.create(company_id: current_user.company.id)
      @conversation.participants.create(company_id: publisher.id)
    end
    @message = @conversation.messages.new()
    @company = @conversation.companies.where("companies.id != ?", current_user.company.id).first
    redirect_to creator_conversation_path(@conversation.messages.first.conversation_id)
  end

  private

  def get_left_bar
    convo_ids = current_user.company.conversations.ids
    @messages = Message.includes(:conversation)
                        .where('messages.id IN (
                            SELECT MAX(messages.id)
                            FROM messages
                            WHERE messages.conversation_id
                            IN (?)
                            GROUP BY messages.conversation_id
                          )', convo_ids)
                        .order("created_at DESC", "id DESC")
  end
end

app/controllers/creator/dashboard_controller.rb
class Creator::DashboardController < Creator::BaseController
  def index
    @videos = current_user.company.videos.includes(:genre)
    @viewership = [
      { created_at: 1.hour.ago.beginning_of_hour.strftime("%H:%M"), views: 566 },
      { created_at: 2.hours.ago.beginning_of_hour.strftime("%H:%M"), views: 400 },
      { created_at: 3.hours.ago.beginning_of_hour.strftime("%H:%M"), views: 303 },
      { created_at: 4.hours.ago.beginning_of_hour.strftime("%H:%M"), views: 353 },
      { created_at: 5.hours.ago.beginning_of_hour.strftime("%H:%M"), views: 210 },
      { created_at: 6.hours.ago.beginning_of_hour.strftime("%H:%M"), views: 308 }
    ]
    @publishers = Company.where(kind: "publisher")
  end
end

app/controllers/creator/messages_controller.rb
class Creator::MessagesController < Creator::BaseController
  def create
    @conversation = current_user.company.conversations.find(params[:conversation_id])
    @message = @conversation.messages.new(message_params)
    if @message.save
      ids = @conversation.companies.ids
      filtered_ids = ids - [current_user.company.id]
      filtered_ids.each do |id|
        ActionCable.server.broadcast "company_#{id}_channel",
          { message: {
              id: @message.id,
              body: @message.body,
              company_name: @message.company.name,
              conversation_id: @conversation.id,
              message_time: @message.message_time,
              cover_image_url: current_user.company.cover_image_url,
              to_kind: "publisher"
            },
            user: current_user
          }
      end
      respond_to do |format|
        format.js
      end
    else
      redirect_to creator_conversation_url(@conversation.id)
    end
  end

  protected

  def message_params
    params.require(:message).permit(:body, :user_id, :conversation_id).merge(user_id: current_user.id, company_id: current_user.company.id)
  end
end

app/controllers/creator/publishers_controller.rb
class Creator::PublishersController < Creator::BaseController
  def show
    @publisher = Company.where(kind: 'publisher').find(params[:id])
    @videos = Video.all.first ? Video.all.limit(4) : []
  end
end

app/controllers/creator/videos_controller.rb
class Creator::VideosController < Creator::BaseController
  def index
    @videos = current_user.company.videos.limit(4)
  end

  def show
    @video = current_user.company.videos.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def new
    set_s3_direct_post
    @video = current_user.company.videos.new()
    respond_to do |format|
      format.js
    end
  end

  def create
    set_s3_direct_post
    @video = current_user.company.videos.new(video_params)
    if @video.save
      redirect_to creator_dashboard_path
    else
      redirect_to creator_dashboard_path
    end
  end

  protected

  def video_params
    params.require(:video).permit(:name, :url, :description, :thumbnail, :genre_id)
  end

  def set_s3_direct_post
    bucket = Aws::S3::Bucket.new(
      access_key_id: ENV['AWS_ACCESS_KEY_ID'],
      secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
      region: 'us-west-2',
      name: ENV['S3_BUCKET']
    )
    @s3_direct_post = bucket.presigned_post(key: "uploads/#{SecureRandom.uuid}${filename}", success_action_status: '201', acl: 'public-read')
  end
end

app/controllers/publisher/creators_controller.rb
class Publisher::CreatorsController < Publisher::BaseController
  def show
    @creator = Company.where(kind: 'creator').all.find(params[:id])
    @videos = @creator.videos.limit(4)
  end
end

app/controllers/publisher/videos_controller.rb
class Publisher::VideosController < Publisher::BaseController
  def show
    @video = Video.find(params[:id])
    respond_to do |format|
      format.js
    end
  end
end

app/views/creator/videos/_new.html.erb
<div class="modal-dialog modal-dialog-centered" role="document">
  <div class="modal-content">
    <%= form_for(@video, url: creator_videos_path, html: { class: 'directUpload', data: { 'form-data' => (@s3_direct_post.fields), 'url' => @s3_direct_post.url, 'host' => URI.parse(@s3_direct_post.url).host } }) do |f| %>
      <div class="new-video-form">
        <div class="video-header">
          <div>
            <span class="video-title"><strong>Video Details</strong></span>
          </div>
          <div class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true"><strong>&times;</strong></span>
          </div>
        </div>
        <div class="video-field">
          <%= f.text_field :name, placeholder: 'name' %>
        </div>
        <div class="video-field">
          <%= f.text_area :description, placeholder: 'description' %>
        </div>
        <div class="video-field">
          <%= f.collection_select :genre_id, Genre.order(:name), :id, :name, {prompt: 'Genre'} %>
        </div>
        <div class="video-field file-field">
          <%= f.label :thumbnail %>
          <%= f.file_field :thumbnail %>
        </div>
        <div class="video-field file-field">
          <%= f.label :url, "Video file" %>
          <%= f.file_field :url %>
        </div>
        <%= f.submit "Submit", class: "button-primary"  %>
      </div>
    <% end %>
  </div>
</div>

app/views/creator/videos/_show.html.erb
<div class="modal-dialog modal-dialog-centered" role="document">
  <div class="modal-content show-video-modal">
    <div class="video-player-container">
      <video class="video-player" poster="<%= @video.thumbnail %>" controls controlsList="nodownload">
        <source src="<%= @video.url %>" type="video/mp4">
      </video>
      <div class="video-player-details">
        <span style="color: #6F3291; font-size: 20px;"><%= @video.name %></span>
        <span style="color: #EC4D77; font-size: 12px;"><%= @video.genre.name %></span>
        <span style="color: #9B9B9B; font-size: 16px;"><%= @video.description %></span>
        <div class="video-bottom">
          <div>
            <div>
              <span style="color: #6F3291; font-size: 12px;">Director - </span>
              <span style="color: #EC4D77; font-size: 12px;">Greg Stanford</span>
            </div>
            <div>
              <span style="color: #6F3291; font-size: 12px;">Producer - </span>
              <span style="color: #EC4D77; font-size: 12px;">Stacy Barnes</span>
            </div>
            <div>
              <span style="color: #6F3291; font-size: 12px;">Actor - </span>
              <span style="color: #EC4D77; font-size: 12px;">Leeroy Jenkins</span>
            </div>
          </div>
          <div>
            <button class="button-secondary">Contracts</button>
            <button class="button-secondary">Analytics</button>
            <button class="button-secondary">Settings</button>
          </div>
        </div>
      </div>
      <div class="video-close close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"><strong>&times;</strong></span>
      </div>
    </div>
  </div>
</div>

app/views/creator/videos/index.html.erb
<h3>videos index</h3>
<%= link_to "New Video", new_creator_video_path %>

<% @videos.each do |video| %>
  <div>
    <img src="<%= video.thumbnail %>" style="max-width: 200px"/>
    <h2><%= video.name %></h2>
    <p><%= video.description %></p>
  </div>
<% end %>

app/views/creator/videos/new.js.erb
$("#new-video-modal").html("<%= escape_javascript(render 'new') %>");
$("#new-video-modal").modal();