config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  
  root to: "home#index"

  namespace :creator do
    get 'dashboard', to: "dashboard#index"
    get 'bazaar/browse',    to: "bazaar#browse"

    resources :conversations, only: [:index, :show] do
      resources :messages, only: [:create]
    end
    get 'conversations/publisher/:id', to: "conversations#publisher"
    resources :videos
    resources :publishers, only: [:show]
  end

  namespace :publisher do
    get 'dashboard', to: "dashboard#index"
    get 'bazaar',    to: "bazaar#browse"

    resources :creators, only: [:show]
    resources :conversations, only: [:index, :show] do
      resources :messages, only: [:create]
    end
    get 'conversations/creator/:id', to: "conversations#creator"
    resources :videos
  end

  get '404', to: 'application#render_404'
  get '*unmatched_route', to: 'application#render_404'
end

app/controllers/creator/dashboard_controller.rb
class Creator::DashboardController < Creator::BaseController
  def index
    @videos = current_user.company.videos.includes(:genre)
    @viewership = [
      { created_at: 1.hour.ago.beginning_of_hour.strftime("%H:%M"), views: 566 },
      { created_at: 2.hours.ago.beginning_of_hour.strftime("%H:%M"), views: 400 },
      { created_at: 3.hours.ago.beginning_of_hour.strftime("%H:%M"), views: 303 },
      { created_at: 4.hours.ago.beginning_of_hour.strftime("%H:%M"), views: 353 },
      { created_at: 5.hours.ago.beginning_of_hour.strftime("%H:%M"), views: 210 },
      { created_at: 6.hours.ago.beginning_of_hour.strftime("%H:%M"), views: 308 }
    ]
    @publishers = Company.where(kind: "publisher")
  end
end

app/controllers/creator/publishers_controller.rb
class Creator::PublishersController < Creator::BaseController
  def show
    @publisher = Company.where(kind: 'publisher').find(params[:id])
    @videos = Video.all.first ? Video.all.limit(4) : []
  end
end

app/controllers/publisher/base_controller.rb
class Publisher::BaseController < AuthorizedController
  before_action :assure_publisher

  protected

  def assure_publisher
    return if current_user.company.publisher?
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/publisher/bazaar_controller.rb
class Publisher::BazaarController < Publisher::BaseController
  def browse
    @creators = Company.where(kind: 'creator').limit(6)
    @creators2 = Company.where(kind: 'creator').order('id DESC').limit(4)
  end
end

app/controllers/publisher/conversations_controller.rb
class Publisher::ConversationsController < Publisher::BaseController
  def index
    get_left_bar
  end

  def show
    get_left_bar
    @conversation = current_user.company.conversations.find_by(id: params[:id])
    if @conversation.nil?
      redirect_to creator_conversations_path
    else
      @message = @conversation.messages.new()
      @company = @conversation.companies.where("companies.id != ?", current_user.company.id).first
      Message.all.where('user_id NOT IN (?) AND conversation_id = ?', current_user.company.users.ids, @conversation.id).update_all(read: true)
    end
  end

  def creator
    get_left_bar
    creator = Company.find(params[:id])
    pub_convo_ids = creator.conversations.ids
    cu_convo_ids = current_user.company.conversations.ids
    found = pub_convo_ids & cu_convo_ids
    @conversation = Conversation.find_by(id: found.first)
    if @conversation.nil?
      @conversation = Conversation.create()
      @conversation.participants.create(company_id: current_user.company.id)
      @conversation.participants.create(company_id: creator.id)
    end
    @message = @conversation.messages.new()
    @company = @conversation.companies.where("companies.id != ?", current_user.company.id).first
    redirect_to publisher_conversation_path(@conversation.messages.first.conversation_id)
  end

  private

  def get_left_bar
    convo_ids = current_user.company.conversations.ids
    @messages = Message.includes(:conversation)
                        .where('messages.id IN (
                            SELECT MAX(messages.id)
                            FROM messages
                            WHERE messages.conversation_id
                            IN (?)
                            GROUP BY messages.conversation_id
                          )', convo_ids)
                        .order("created_at DESC", "id DESC")
  end

end

app/controllers/publisher/creators_controller.rb
class Publisher::CreatorsController < Publisher::BaseController
  def show
    @creator = Company.where(kind: 'creator').all.find(params[:id])
    @videos = @creator.videos.limit(4)
  end
end

app/controllers/publisher/dashboard_controller.rb
class Publisher::DashboardController < Publisher::BaseController
  def index
    @videos = Video.all.limit(5).includes(:genre)
    @viewership = [
      { created_at: 1.hour.ago.beginning_of_hour.strftime("%H:%M"), views: 288 },
      { created_at: 2.hours.ago.beginning_of_hour.strftime("%H:%M"), views: 401 },
      { created_at: 3.hours.ago.beginning_of_hour.strftime("%H:%M"), views: 303 },
      { created_at: 4.hours.ago.beginning_of_hour.strftime("%H:%M"), views: 853 },
      { created_at: 5.hours.ago.beginning_of_hour.strftime("%H:%M"), views: 1010 },
      { created_at: 6.hours.ago.beginning_of_hour.strftime("%H:%M"), views: 908 }
    ]
    @publishers = Company.where(kind: "creator")
  end
end

app/controllers/publisher/messages_controller.rb
class Publisher::MessagesController < Publisher::BaseController
  def create
    @conversation = current_user.company.conversations.find(params[:conversation_id])
    @message = @conversation.messages.new(message_params)
    if @message.save
      ids = @conversation.companies.ids
      filtered_ids = ids - [current_user.company.id]
      filtered_ids.each do |id|
        ActionCable.server.broadcast "company_#{id}_channel",
          { message: {
              id: @message.id,
              body: @message.body,
              company_name: @message.company.name,
              conversation_id: @conversation.id,
              message_time: @message.message_time,
              cover_image_url: current_user.company.cover_image_url,
              to_kind: "creator"
            }, 
            user: current_user
          }
      end
      respond_to do |format|
        format.js
      end
    else
      redirect_to publisher_conversation_url(@conversation.id)
    end
  end

  protected

  def message_params
    params.require(:message).permit(:body, :user_id, :conversation_id).merge(user_id: current_user.id, company_id: current_user.company.id)
  end
end

app/controllers/publisher/videos_controller.rb
class Publisher::VideosController < Publisher::BaseController
  def show
    @video = Video.find(params[:id])
    respond_to do |format|
      format.js
    end
  end
end

app/views/publisher/dashboard/index.html.erb
<div class="dashboard-grid">
  <div class="videos-column">
    <div class="column-header">
      <span class="column-title">
        <strong>Your Content</strong>
      </span>
    </div>
    <div class="videos-column-list">
      <% @videos.each do |video| %>
        <div class="video-item-container">
          <img src="<%= video.thumbnail %>"/>
          <div class="video-item">
            <div class="video-item-details">
              <span class="purple"><strong><%= video.name %></strong></span>
              <span class="grey"><small><%= video.genre.name %></small></span>
              <span class="pink"><%= [693, 667, 19, 208, 770].sample %> Views</span>
              <span class="pink"><%= [293, 9667, 191, 2008, 7830].sample %> Revenue</span>
            </div>
            <%= link_to publisher_video_path(video.id), {remote: true, 'data-toggle':  "modal", render_layout: false} do %>
              <button class="button-primary video-item-button">DETAILS</button>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="bullshit-column">
    <div class="graph-row">
      <div class="viewership">
        <div class="column-title">
          <span>
            <strong>Live Viewership</strong>
          </span>
        </div>
        <%= area_chart @viewership.group_by { |u| u[:created_at] }.map { |k,v| [k, v[0][:views]] },
          id: "users-chart", colors: ["#EC4D77"], points: false, defer: true
        %>
      </div>
      <div class="revenue">
        <%= pie_chart(
          {"PPV": 700, "Advertisements": 3015, "Donations": 1607},
          id: "fuck-all", legend: false, defer: true, colors: ["#EC4D77", "#6F3291", "#9B9B9B"], height: "80%", width: "50%"
        )%>
        <div class="revenue-title-container">
          <div class="monetization-title"><span><strong>Monetization</strong></span></div>
          <div class="money-title"><span><strong>$12,357</strong></span></div>
        </div>
      </div>
    </div>
    <div class="statistics">
      <div class="stat">
        <div class="stat-top">
          <span><strong>132</strong></span>
        </div>
        <div class="stat-bottom">
          <span><strong>Total Subscribers</strong></span>
        </div>
      </div>
      <div class="stat">
        <div class="stat-top">
          <span><strong>$ 456.60</strong></span>
        </div>
        <div class="stat-bottom">
          <span><strong>Today's Revenue</strong></span>
        </div>
      </div>
      <div class="stat">
        <div class="stat-top">
          <span><strong>16:45:36</strong></span>
        </div>
        <div class="stat-bottom">
          <span><strong>Live Uptime</strong></span>
        </div>
      </div>
    </div>
    <div class="contracts-container">
      <span style="margin-left: 15px; color: #6F3291;">Ongoing Contracts</span>
      <div class="contracts">
        <% @publishers.each do |pub| %>
          <div class="contract-item">
            <img src="<%= pub.cover_image_url %>" />
            <div class="contract-item-details">
              <span style="color: #6F3291; font-size: 16px;"><strong><%= pub.name %></strong></span>
              <span style="color: ##9B9B9B; font-size: 12px;"><%= pub.description %></span>
            </div>
            <div class="card-item-button-container">
              <%= link_to publisher_creator_path(pub.id), {remote: true, 'data-toggle':  "modal", render_layout: false} do %>
                <button class="button-primary video-card-button">DETAILS</button>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="modal" id="show-video-modal" tabindex="-1" role="dialog" aria-hidden="true">
</div>

<div class="modal" id="creator-show-modal" tabindex="-1" role="dialog" aria-hidden="true">
</div>